version: '3'

services:
    kong-database:
        image: postgres:9.4
        environment:
            - POSTGRES_USER=kong
            - POSTGRES_DB=kong
    kong:
        build: 
            context: .
            dockerfile: kong/Dockerfile
        restart: always
        links:
            - kong-database:kong-database
        environment:
            - KONG_DATABASE=postgres
            - KONG_PG_HOST=kong-database
            - KONG_CASSANDRA_CONTACT_POINTS=kong-database
        ports:
            - 80:8000
            - 8443:8443
            - 8001:8001
            - 8444:8444
